(function($, undefined) {
	$.Resources = $.Resources || {};
	$.fn.extend($.Resources, { 
		Strings: { 
			AccessMaintenance: 'Manutenção de Acessos',
			Active: 'Ativo',
			Address: 'Endereço',
			AddressNumber: 'Número',
			Administration: 'Administração',
			Back: 'Voltar',
			Area: 'Área (m2)',
			BoolYesNo: '{0:Sim;0;Não}',
			BusinessUnitMaintenance: 'Manutenção de Empresas',
			Cancel: 'Cancelar',
			City: 'Cidade',
			CorporateName: 'Razão Social',
			Country: 'País',
			Date: 'Data',
			DeleteDate: 'Data da Exclusão',
			Description: 'Descrição',
			DeleteMessage: 'Excluir mensagem',
			Email: 'Email',
			EmailMaintenance: 'Manutenção de Email(Portal)',
			Entries: 'Cadastros',
			Error_InvalidMessage: 'Mensagem inválida.',
			Error_InvalidTitle: 'Título inválido.',
			Error_InvalidUser: 'Usuário inválido.',
			Error_MessageReadFailure: 'Falha na leitura da mensagem',
			FederationUnit: 'UF',
			FloorPlanMaintenance: 'Manutenção de Plantas',
			GeographicAreaMaintenance: 'Manutenção de Áreas Geograficas',
			Height: 'Altura (cm)',
			Id: 'Id',
			Inbox: 'Caixa de entrada',
			Length: 'Comprimento (cm)',
			Login: 'Login',
			MessageCentral: 'Central de Mensagens',
			MessageText: 'Corpo da Mensagem',
			Name: 'Nome',
			NewMessage: 'Nova mensagem',
			NoMessagesOnInbox: 'Nenhuma mensagem na caixa de entrada.',
			NoMessagesOnTrash: 'Nenhuma mensagem na lixeira',
			Parent: 'Superior',
			Password: 'Senha',
			ProductMaintenance: 'Manutenção de Produtos',
			ReadDate: 'Data da Leitura',
			ReadMessage: 'Ler mensagem',
			Recipient: 'Destinatário',
			RecoverMessage: 'Recuperar mensagem',
			Repply: 'Responder',
			RoleMaintenance: 'Manutenção de Perfis',
			RoutesMaintence: 'Manutenção de Rotas',
			Send: 'Enviar',
			Sender: 'Remetente',
			SKU: 'SKU',
			SocialCode: 'CPF',
			State: 'Estado',
			StorageGroupMaintenance: 'Manutenção de Grupos de Armazenagem',
			Success_Operation: 'Operação realizada com sucesso.',
			Title: 'Título',
			Trash: 'Lixeira',
			TrashMessage: 'Apagar mensagem',
			UnitMaintenance: 'Manutenção de Unidades',
			UserMaintenance: 'Manutenção de Usuários',
			Weight: 'Peso (Kg)',
			Width: 'Largura',
			User: 'Usuário',
			LotControl: 'Controla Lote',
			Code: 'Código',
			DepositorId: 'ID Depositante',
			ExpirationDate: 'Data de Validade',
			GridControl: 'Controla Grade',
			PurchaseUnit: 'Unidade de Entrada',
			SalesUnit: 'Unidade de Picking',
			ShelfLife: 'Shelf Life (Dias)',
			StorageUnit: 'Unidade de Armazenagem',
			ValidityControl: 'Controla Validade',
			BarCode: 'Código de Barra',
			SKUMaintenance: 'Manutenção do SKU',
			PackQuantity: 'Quantidade por Embalagem',
			Volumem3: 'Volume (m3)',
			UserRolesAdministration: 'Manutenção de Perfis do usuário',
			AvailableRoles: 'Perfis Disponíveis',
			CurrentRoles: 'Perfis Atuais',
			Error_InvalidUnit: 'Unidade Inválida',
			Product: 'Produto',
			Unit: 'Unidade',
			DepositorMaintenance: 'Manutenção de Depositantes',
			Depositor: 'Depositante',
			StorageUnitT: 'Grupo de Armazenagem',
			SupplierMaintenance: 'Manutenção de Fornecedores',
			Welcome: 'Bem vindo ao WMS Control.',
			DockMaintenance: 'Manutenção de Docas',
			FloorPlan: 'Planta',
			Vacancies: 'Número de Vagas',
			PatioMaintenance: 'Manutenção do Patio',
			VacanciesMaintenance: 'Manutenção de Vagas',
			Patio: 'Patio',
			Yard: 'Patio',
			AddressMaintenance: 'Manutenção de Endereço',
			Apartment: 'Apartamento',
			Block: 'Bloco',
			Level: 'Nível',
			MaxWeight: 'Peso Maximo',
			Side: 'Lado',
			Street: 'Rua',
			Addressing: 'Endereçamento',
			Ammount: 'Quantidade',
			Lot: 'Lote',
			Order: 'Pedido',
			OrderManifest: 'Manifesto',
			OrderType: 'Tipo de Pedido',
			Price: 'Preço',
			VariableWeight: 'Peso Variável',
			OrderMaintenance: 'Manutenção do Pedido',
			OrderItemMaintenance: 'Manutenção do Item do Pedido',
			OrderManifestMaintenance: 'Manutenção do Manifesto',
			OrderTypeMaintenance: 'Manutenção do Tipo de Pedido',
			Entry: 'Entrada',
			OrderTypeMaintenances: 'Manutenção do Tipo do Pedido',
			Orders: 'Pedidos',
			Error_InvalidEmail: 'Erro! Email Inválido',
			Error_InvalidLogin: 'Erro! Login Inválido',
			Error_InvalidName: 'Erro! Nome Inválido',
			Error_InvalidPassword: 'Erro! Senha Inválida',
			SimpleDateFormat: '{0:dd/MM/yyyy}',
			CurrencyFormat: '{0:R$ #0.00}',
			Factor: 'Fator',
			InvoiceNumber: 'Nota Fiscal',
			Issued: 'Destinatário',
			Issuer: 'Fornecedor',
			Number: 'Número',
			Error_InvalidDocumentDate: 'Data do documento inválido.',
			Error_InvalidDocumentNumber: 'Número do documento inválido.',
			DocumentInputMonitor: 'Monitor de Entradas',
			DocumentTypeMaintenance: 'Manutenção de tipos de documentos',
			DocumentType: 'Tipo de Documento',
			Error_InvalidDocumentIssued: 'Destinatário do documento inválido.',
			Items: 'Itens',
			AddItem: 'Adicionar Item',
			Checked: 'Conferido',
			Delete: 'Excluir',
			Edit: 'Editar',
			PartiallyChecked: 'Conferência Parcial',
			PartiallyStored: 'Armazenagem Parcial',
			Stored: 'Armazenado',
			ContinueAddingItems: 'Clique em continuar para adicionar mais itens ao documento, ou feche a janela para concluir.',
			Continue: 'Continuar',
			DocumentSteps: 'Etapas do Documento',
			Cancelled: 'Cancelado',
			Confered: 'Conferido',
			Interned: 'Internado',
			Registered: 'Registrado',
			Persons: 'Pessoas',
			Products: 'Produtos',
			AreYouSureToDelete: 'Tem certeza que deseja excluir este registro?',
			RegisterDeletion: 'Exclusão de Registro',
			No: 'Não',
			Yes: 'Sim',
			Save: 'Salvar',
			DocumentOutputMonitor: 'Monitor de Saídas',
			CustomerMaintenance: 'Manutenção de Cliente',
			GroupOne: 'Grupo 1',
			GroupRestrictionMaintenance: 'Restrição do Grupo de Armazenagem',
			GroupTwo: 'Grupo 2',
			Restrictions: 'Restrições',
			Error_StorageGroupCantBeTheSame: 'Erro! Os grupos de armazenagem não podem ser iguais.',
			Error_RestrictionAlreadyRegistered: 'Esta restrição já foi registrada.',
			Error_InvalidStorageGroup: 'Grupo de Armazenagem inválido.',
			BlindNoteGeneration: 'Geração de Nota Cega',
			DocumentInputs: 'Documentos de Entrada',
			Details: 'Detalhes',
			Error_BlindNoteAlreadyGenerated: 'Nota cega já gerada para a entrada especificada.',
			Error_NoResultsFoundWithMatchingCriteria: 'Nenhum resultado encontrado com os critérios informados.',
			Checker: 'Conferente',
			Document: 'Documento',
			Error_InvalidConfigClass: 'Classe de configuração inválida.',
			Error_InvalidConnectionString: 'Configuração de conexão de dados inválida.',
			Error_InvalidXml: 'Arquivo XML inválido.',
			Separator: 'Separador',
			BlindNote: 'Nota Cega',
			BlindNoteCheck: 'Conferência de Nota Cega',
			BlindNoteDivergence: 'Divergências de Nota Cega',
			Checking: 'Conferência',
			Client: 'Cliente',
			DocumentOutput: 'Documento de Saída',
			Flowhack: 'Flowrack',
			InputProcess: 'Processo de entrada',
			Manifest: 'Manifesto',
			OutputProcess: 'Processo de Saída',
			RestrictionsStorage: 'Restrições de Armazenagem',
			Separation: 'Separação',
			Storage: 'Depósito',
			AddressesWithoutCounting: 'Endereços sem contagem',
			AddressesWithoutDrive: 'Endereços sem Unidade',
			AddressGlanceFilters: 'Address Glance Filters ',
			AllCounts: 'Todos as Contagens',
			CheckInOutVehicle: 'Controle de Veiculos',
			Conference: 'Conferência',
			DevergenceOfCount: 'Divergências entre Contagens',
			ConsolidatedBySKU: 'Consolidado por SKU',
			ConsultationsReports: 'Consulta de Relatórios',
			ControlOrdinance: 'Controle de Portaria',
			DivegenceFoReCount: 'Divergências para nova contagem',
			EntryDocument: 'Documento de Entrada',
			Export: 'Exportação',
			GenerationInventory: 'Geração de Inventário',
			Inventory: 'Inventário',
			InventoryTyping: 'Tipo de Inventário',
			KPIGraphics: 'Gráficos de KPI',
			LabelPrinting: 'Impressão de Etiquetas',
			LogisticsDataAnalysis: 'Análise de Dados Logística',
			OccupationofDeposit: 'Ocupação do Deposito',
			OverviewOfSKUsWithFilters: 'Visão Geral dos SKUs Com Filtros',
			Picking: 'Picking',
			PositionBySKU: 'Posicionado por SKU',
			Productivity: 'Produtividade',
			ProductivityOperatorsDeposit: 'Produtividade Operadores do Depósito',
			Receiving: 'Recebimento',
			Reports: 'Relatórios',
			ReservedAddress: 'Endereço Reservado',
			ReSupply: 'Re Abastecimento',
			SeparationMap: 'Mapa de Separação',
			Shipping: 'Expedição',
			SKUByLots: 'SKU por Lotes',
			SKUWithoutDrive: 'SKU sem Unidade',
			Structures: 'Estruturas',
			Temporarily: 'Temporário',
			ValidityofSKUs: 'Validade dos SKU\'s',
			VisionDeposit: 'Visão do Deposito',
			WMSxERP: 'WMSxERP',
			DocumentInputCheck: 'Conferência de Documentos de Entrada',
			Allocation: 'Alocação',
			Result: 'Resultados',
			Allocate: 'Alocar',
			Search: 'Localizar',
			DocumentOutputs: 'Documentos de Saída',
			Warning: 'Atenção',
			LinesPerPage: 'Linhas',
			Error_InvalidDocumentIssuer: 'Emitente inválido.',
			Error_InvalidDocumentType: 'Tipo de Documento Inválido',
			Error_InvalidBusinessUnit: 'Empresa inválida.',
			BusinessUnit: 'Empresa',
			Error: 'Erro',
			Error_NoDataSelected: 'Nenhum dado selecionado.',
			DocumentInput: 'Documento de Entrada',
			Error_InvalidProduct: 'Produto inválido.',
			Error_InvalidUserNameOrPassword: 'Nome de usuário ou senha inválidos.',
			Access: 'Acesso',
			LoginOrEmail: 'Login ou Email',
			LostPassword: 'Perdi minha senha.',
			Success: 'Sucesso',
			UsersAdministration: 'Manitenção de Usuários.',
			Error_InvalidSocialCode: 'CPF inválido.',
			PasswordConfirmation: 'Confirmação de Senha',
			Error_PasswordAndConfirmationDoesntMatch: 'A senha e a confirmação não conferem.',
			Users: 'Usuários',
			Depositors: 'Depositantes',
			EnterpriseMaintanance: 'Manutenção de Empresas',
			Enterprises: 'Empresas',
			Error_InvalidCity: 'Cidade Inválida',
			Error_InvalidUF: 'UF inválida',
			CorporateCode: 'CNPJ',
			StorageGroups: 'Grupos de Armazenagem',
			Units: 'Unidades',
			Error_InvalidCode: 'Código Inválido',
			StorageGroup: 'Grupo de Armazenagem',
			Enterprise: 'Empresa',
			ExpirationControl: 'Controle de Validade',
			SKUs: 'SKUs',
			PackAmmount: 'Qt. por Embalagem',
			Error_InvalidBarCode: 'Código de barras inválido',
			Error_InvalidHeight: 'Altura inválida',
			Error_InvalidLength: 'Comprimento inválido',
			Error_InvalidPackAmmount: 'Qt. por pacote inválido.',
			Error_InvalidVolume: 'Volume inválido',
			Error_InvalidWeight: 'Peso inválido',
			Error_InvalidWidth: 'Largura inválida',
			Addresses: 'Endereços',
			BuildingMaintenance: 'Manutenção de Plantas',
			Buildings: 'Plantas',
			Docks: 'Docas',
			GeographicAreas: 'Áreas Geográficas',
			YardMaintenance: 'Manutenção de Pátios',
			Yards: 'Pátios',
			FU: 'UF',
			Building: 'Planta',
			Even: 'Par',
			Odd: 'Ímpar',
			Error_InvalidApartment: 'Apartamento Inválido',
			Error_InvalidBlock: 'Bloco inválido',
			Error_InvalidLevel: 'Nível inválido',
			Error_InvalidStreet: 'Rua inválida',
			MovingProcess: 'Processo de Movimentação',
			MovingProduct: 'Movimentação de Produtos',
			AllocationConfirmation: 'Confirmação da Alocação',
			AllocationSKU: 'Internação de SKU',
			ConferenceVolumesOrdinances: 'Conferência de Volume',
			FlowrackCheck: 'Conferência do Flowrack',
			OrderCheck: 'Conferência de Pedidos',
			ShippingConference: 'Conferência de Volumes Portaria',
			Traceability: 'Rastreabilidade',
			Activity: 'Atividade',
			ActivityTraceability: 'Rastreabilidade de Atividades',
			ConfirmationAllocation: 'Confirmação de Alocação',
			DocumentCode: 'Código do Documento',
			Driver: 'Motorista',
			FlowrackChecker: 'Conferência de Flowrack',
			Lecturer: 'Conferente',
			ManifestCheck: 'Conferência de Manifesto',
			OriginalAdress: 'Endereço de Origem',
			OutstandingVolumes: 'Volumes Pendentes',
			Period: 'Período',
			ProductCheck: 'Checagem de Produto',
			Supplier: 'Fornecedor',
			Validity: 'Validade',
			Vehicle: 'Veículo',
			PendingVolume: 'Volumes Pendentes',
			DestinationAdress: 'Endereço de Destino',
			Season: 'Estação',
			Allocations: 'Internados',
			Destination: 'Destino',
			Mirror: 'Espelho',
			Pending: 'Pendentes',
			Source: 'Origem',
			TotalVolume: 'Total de Volumes',
			Close: 'Fechar',
			Palletizing: 'Paletização',
			Error_RequiredRestriction: 'Informe uma Restrição',
			StorageGroupRestrictionMaintenance: 'Restrições do Grupo de Armazenamento',
			StorageGroupRestrictions: 'Restrições do Grupo de Armazenagem',
			Customer: 'Cliente',
			Error_CNPJNotFound: 'Erro! CNPJ ou CPF Não Encontrado.',
			Error_EnterpriseAlreadyExist: 'Empresa Já Cadastrada.',
			Error_DepositorAlreadyExist: 'Depositante Já Cadastrado',
			Error_SupplierAlreadyExist: 'Fornecedor Já Cadastrado',
			Error_UserAlreadyExist: 'Usuário Já Cadastrado',
			FindOrders: 'Localizar Pedidos',
			FindRequest: 'Documento de Saída',
			RequestItemMaintenance: 'Manutenção Itens da Compra',
			RequestManifest: 'Manifesto de Saída ',
			Error_OrderAlreadyChecked: 'O pedido já foi conferido.',
			Error_OrderDoesNotExist: 'Erro! Pedido não existe.',
			Error_OrderDoesntHaveItems: 'Erro! O pedido não possui itens.',
			Error_RequestAlreadyChecked: 'Erro! Pedido já conferido.',
			Error_RequestDoesNotExist: 'Erro! Pedido não existe.',
			Error_RequestDoesntHaveItems: 'Erro! Pedido não tem items.',
			Request: 'Entrada',
			EndConference: 'Fim de Conferência',
			Functions: 'Funcionalidades',
			ProductConference: 'Conferência de Produtos',
			RequestDate: 'Data de Entrada',
			StartConference: 'Início de Conferência',
			Erro_ProductDoesNotExist: 'Erro! Esse Produto Não Existe',
			InitialDate: 'Data Inicial',
			ProductCode: 'Código do Produto',
			Erro_InvalidAmmount: 'Erro! Quantidade Invalida',
			Erro_ItemAlreadyChecked: 'Erro! Item já foi checado.',
			Error_AmmountInvalid: 'Erro! Pedido não conferido corretamente.',
			Error_MissingItens: 'Erro! Itens faltando na conferencia.',
			RequestCheck: 'Checagem do Pedido.',
			Input: 'Entrada',
			Operation: 'Operação',
			Output: 'Saída',
			VehicleControl: 'Coontrole de Veículo',
			Admission: 'Internação',
			AdressWhitoutMoving: 'Endereço Sem Movimentação',
			EmployeesProductivity: 'Produtividade Colaboradores',
			EnteringtheCounts: 'Digitação Das Contagens',
			ExportData: 'Exportar Dados',
			Flowrack: 'Flowrack',
			OverviewAdress: 'Visão Geral de Endereços',
			OverviewSKUs: 'Visão Geral de SKUs',
			ReservedAdress: 'Endereços Reservados',
			SKUWhithoutMoving: 'SKU Sem Movimentação',
			StockWMSxERP: 'Estoque WMS x ERP',
			Closed: 'Fechado',
			DateClosed: 'Data de Fechamento',
			DateOpened: 'Data de Abertura',
			InventoryAdress: 'Inventário Por Endereço',
			InventoryDopositor: 'Inventário Por Depositante',
			InventoryGeneral: 'Inventário Geral',
			InventorySKU: 'Inventário Por SKU',
			Open: 'Aberto',
			Situation: 'Situação',
			Person: 'Pessoa',
			ConsultationReport: 'Consultas / Relatorios',
			Adress: 'Endereço',
			ImpressionLabelAdmission: 'Impressão de Etiquetas de Internação',
			ImpressionLabel: 'Imprimir Etiquetas',
			ImpressionLabelExpedition: 'Impressão de Etiquetas de Expedição',
			ImpressionLabelFlowrack: 'Impressão de Etiquetas de Flowrack',
			Volume: 'Volume',
			ControlFlow: 'Controle do Fluxo',
			Flow: 'Fluxo',
			Ordinance: 'Portaria',
			Volumes: 'Volumes',
			Deposit: 'Deposito',
			Basic: 'Básico',
			Planned: 'Planejadas',
			ResupplyBasicPlanned: 'Ressuprimento - Básico e Planejado',
			Type: 'Tipo',
			Waves: 'Ondas',
			AdressArmazen: 'End. Armazenagem',
			AdressPrincipal: 'End. Principal',
			Expedition: 'Expedição',
			ReservedAddresses: 'Endereços Reservados',
			AddressType: 'Tipo de Endereço',
			ActiveProducts: 'Ativos',
			All: 'Todos',
			Analytical: 'Analítico',
			InactiveProducts: 'Inativos',
			Status: 'Status',
			Stock: 'Estoque',
			StockStatus: 'Status do Estoque',
			Synthetic: 'Sintético',
			WithoutStock: 'Sem estoque',
			WithStock: 'Com estoque',
			AdressWithoutMove: 'Endereço Sem Movimentação',
			DifferencesReportRecount: 'Relatório de Divergências para Nova Contagem',
			DivergenceReportScores: 'Relatório de Divergências de Contagem',
			InventoryProductivityReport: 'Relatório de Produtividade do Inventário',
			RegisterFlow: 'Cadastro do Fluxo (Entrada / Saída)',
			ReportAllCounts: 'Relatório de todas as contagens',
			DivergenceStockWMSxERP: 'Divergência de ERP x WMS',
			FinalDate: 'Data Final',
			InventoryProductivity: 'Produtividade do Inventário',
			AdressPicking: 'End. de Picking',
			SKUNotMoving: 'SKU Sem Movimentação',
			AdressWhitoutCount: 'Endereços Sem Contagem',
			AreYouSureToExport: 'Tem certeza que deseja exportar os dados do inventário?',
			ExportInventoryData: 'Exportar dados do inventário',
			ThereIsNoDataToExport: 'Não há dados a serem exportados.',
			CancelInventory: 'Cancelar Inventário',
			CloseInventory: 'Fechar Inventário',
			ExportDataInventory: 'Exportar Dados do Inventário',
			GenerateCount: 'Gerar Contagem',
			TypingCount: 'Digitação da Contagem',
			AvailableRequests: 'Entradas disponíveis',
			Erro_ProductDoesNotExisteInRequest: 'Erro! Produto não existe no pedido.',
			Lack: 'Falta',
			RemoveItens: 'Remover Itens',
			ResetConference: 'Resetar Conferência',
			AreYouSureToResetTheConference: 'Tem certeza que deseja resetar a conferência?',
			PersonManagement: 'Manutenção de Pessoas',
			Error_CorporateCodeAlreadyRegistered: 'CNPJ já cadastrado',
			Error_NullCorporateSocialCode: 'CNPJ ou CPF não podem ser nulos.',
			Error_NullName: 'O nome deve ser informado.',
			Error_SocialCodeAlreadyRegistered: 'CPF já cadastrado',
			ActionManagement: 'Manutenção de Ações',
			Actions: 'Ações',
			Controller: 'Controlador',
			Module: 'Módulo',
			Action: 'Ação',
			Create: 'Novo',
			EditActions: 'Editar Ações',
			ProfileManagement: 'Manutenção de Perfis',
			Profiles: 'Perfis',
			UserManagement: 'Manutenção de Usuários',
			Warehouse: 'Depósito',
			WarehouseManagement: 'Manutenção de Depósitos',
			Warehouses: 'Depósitos',
			ApartmentsPerLevel: 'Apartamentos por Nível',
			Blocks: 'Blocos',
			CreateAddresses: 'Criar Endereços',
			DefaultHeightInCm: 'Altura (cm)',
			DefaultLengthInCm: 'Comprimento (cm)',
			DefaultPickingLevel: 'Nível de Picking Padrão',
			DefaultWeightInKg: 'Peso (kg)',
			DefaultWidthInCm: 'Largura (cm)',
			Error_NoAddressesFoundForWarehouse: 'Nenhum endereço cadastrado no depósito',
			Levels: 'Níveis',
			Streets: 'Ruas',
			CheckedItems: 'Itens Conferidos',
			Difference: 'Diferença',
			Error_ProductIsntInOrder: 'Oproduto não existe no pedido.',
			Divergence: 'Divergência',
			Error_OrderCheckIsFinished: 'A conferência do pedido já foi finalizada',
			Error_OrderCheckNotFound: 'Não foi encontrada nenhuma conferência de pedidos com o código informado.',
			Error_ProductInvalidForOrder: 'Produto não existe no pedido.',
			Requests: 'Entradas',
			Error_InvalidOrderManifest: 'Manifesto inválido.',
			Error_InvalidOrderManifestChecking: 'Conferência de manifesto inválida.',
			Error_ManifestCheckingAlreadyFinished: 'O manifesto já foi conferido.',
			Error_ManifestDoesntExist: 'O manifesto não existe.',
			Error_ProductDoesntExistOnThisManifest: 'O produto não existe no manifesto atual.',
			Error_ProductDoestNotExist: 'O produto não existe.',
			OrderManifestChecking: 'Conferência de Manifesto',
			SkuDataAnalysis: 'Análise de Dados Logísticos de SKU\'s',
			DefaultPallet: 'Palete Padrão',
			MaxStack: 'Altura Máxima (CX/Unid)',
			LifeCycle: 'Vida útil (dias)',
			Pickings: 'Pickings',
			Capacity: 'Capacidade',
			RefillAmmount: 'Reabastecimento',
			DeleteConfirmation: 'Confirmação de Exclusão',
			Error_InvalidAddress: 'Endereço inválido',
			Error_InvalidWarehouse: 'Depósito inválido',
			Error_InvalidCapacity: 'Capacidade inválida',
			Error_CapacitySmallerThanRefillAmmount: 'A capacidade não pode ser inferior ao ponto de reabastecimento',
			Error_CapacityMustBeInformed: 'A capacidade deve ser informada.',
			Error_PickingAlreadyRegisteredForProduct: 'Já existe um picking para o produto cadastrado para o tipo de endereço informado.',
			Ballast: 'Lastro',
			DefaultWeight: 'Peso padrão',
			MaxStorageLevel: 'Nível Máximo de Armazenagem',
			WeigthMustBeInformedForProductThatDoesntHaveDefault: 'O peso deve ser informado quando o produto não possui peso padrão.',
			InvalidMaxHeightForBoxing: 'Altura máxima inválida para paletização.',
			InvalidPallet: 'Palete inválido',
			AddressTypeMaintenance: 'Manutenção do Tipo de Endereço.',
			Routes: 'Rotas',
			OrderSeparation: 'Separação do Pedido',
			SeparatorMaintenance: 'Manutenção de Separador',
			Error_SeparatorDoesNotExist: 'Erro! Separador não existe.',
			Error_OrderAlreadySepared: 'Erro! Pedido já separada.',
			SkuDoesNotExist: 'SKU não existe',
			Error_InvalidSku: 'Sku inválido',
			LotMustBeInformedForProductsThatAreConfigured: 'O lote deve ser informado para este produto.',
			Error_InvalidPerson: 'Pessoa inválida.',
			CheckerMaintenance: 'Manutenção de Conferente.',
			Customers: 'Clientes',
			Separators: 'Separadores',
			Suppliers: 'Fornecedores',
			Error_SelectAWarehouse: 'Selecione um depósito',
			Error_ExpirationDateMustBeInformed: 'A data de validade deve ser informada para este produto.',
			Error_InactiveProduct: 'Produto inativo.',
			Error_LotMustBeInformed: 'O lote deve ser informado para este produto.',
			Error_WeightMustBeInformed: 'O peso deve ser informado para este produto.',
			SKUCode: 'Codigo do SKU',
			Internation: 'Internação',
			RequestNumberExtended: 'Número do Pedido/Compra ou O/P',
			Intern: 'Internar',
			Error_InvalidCorporateCode: 'CNPJ inválido',
			TheCustomerIsAlreadyRegistered: 'Já existe uma pessoa cadastrada no sistema com o CPF/CNPJ informado. Deseja atualizar os dados e incluí-la como cliente?',
			Atention: 'Atenção',
			TheDepositorIsAlreadyRegistered: 'Já existe uma pessoa cadastrada no sistema com o CPF/CNPJ informado. Deseja atualizar os dados e incluí-la como depositante?',
			TheEnterpriseIsAlreadyRegistered: 'Já existe uma pessoa cadastrada no sistema com o CPF/CNPJ informado. Deseja atualizar os dados e incluí-la como empresa?',
			TheSupplierIsAlreadyRegistered: 'Já existe uma pessoa cadastrada no sistema com o CPF/CNPJ informado. Deseja atualizar os dados e incluí-la como fornecedor?',
			AutomaticInternation: 'Internação Automática',
			ManualInternation: 'Internação Manual',
			PrintLabels: 'Imprimir Etiquetas',
			RequestNumber: 'Nº do Doc. de Entrada',
			ViewInternationInfo: 'Informações de internação',
			InternedAmmount: 'Qt. Internada',
			InternedWeight: 'Peso Internado',
			MissingAmmount: 'Qt. Faltando',
			MissingWeight: 'Peso Faltando',
			Error_ProductNotHavecubage: 'Erro! Produto não tem cubagem.',
			Erro_ProductNotExistBarCode: 'Erro! Esse produto não tem código de barra.',
			Error_ProductNotInPicking: 'Erro! Produto não está no Picking.',
			Error_RequestDoesntExistsForTheSelectedEnterprise: 'Pedido inexistente para a empresa selecionada.',
			Error_AmmountNotZero: 'Erro! Quantidade Inválida.',
			Error_InvalidExpiration: 'Erro! Validade Inválida.',
			ValidityDate: 'Data de Validade',
			QueryAddress: 'Consulta de Endereços',
			FinalBlock: 'Bloco Final',
			FinalStreet: 'Rua Final',
			InitialBlock: 'Bloco Inicial',
			InitialStreet: 'Rua Inicial',
			Error_MissingSkuForStorageUnit: 'Não existe SKU de armazenagem para o produto cadastrado.',
			Error_MissingPickingForTheSelectedProduct: 'Não há endereço de picking cadastrado para o produto.',
			Error_MissingLenHeiWid: 'Não existe cadastro de altura, largura e comprimento para o produto selecionado.',
			ProductNotMoving: 'Produto sem movimentação',
			Error_LifeCycleSmallerThanAllowed: 'A validade do produto é inferior à mínima permitida para a armazenagem.',
			Error_ShelflifeSmallerThanAllowed: 'O tempo de ShelfLife do produto é inferior ao mínimo permitido para armazenagem.',
			Error_ExpirationDateIsImpossible: 'A data de validade informada excede os dias de vida útil do produto.',
			InternationMap: 'Mapa de Internação',
			InternateSelectedItems: 'Internar itens selecionados.',
			PrintInternationLabels: 'Imprimir etiquetas de internação.',
			Error_InvalidAddressType: 'Erro! Tipo de endereço inválido',
			Error_InvalidMaxWeight: 'Erro! Máximo peso inválido',
			Infos: 'Informações',
			Tips: 'Dicas',
			InternationStatus: 'Status da Internação',
			InternationFailure: 'Falha na internação',
			InternedSuccessfully: 'Internado com sucesso',
			CanBeInterned: 'Pode ser internado.',
			ValidateSelectedItems: 'Validar itens selecionados',
			Error_InformedAmmountIsHigherThanSupportedByPallet: 'A quantidade informada é superior à capacidade do Pallet.',
			Error_AddresIsNotEmpty: 'O endereço não está vazio',
			StockByAddress: 'Estoque por endereço',
			PrintPositionMap: 'Imprimir Relatório de Posições',
			NoInternationForTheSelectedRequest: 'Não há informações de internação para o registro selecionado.',
			BasicUnit: 'Unidade Básica',
			Error_PickingAddressNotFoundForTheProduct: 'Picking não encontrado para o produto {0} - {1}.',
			Error_BasicUnitSkuNotFoundTheProduct: 'SKU da Unidade Básica não cadastrado para o produto {0} - {1}.',
			Error_StorageSkuNotFoundTheProduct: 'Produto sem SKU de armazenagem {0} - {1}.',
			Manifests: 'Manifestos',
			Error_InvalidArea: 'Erro! Área Inválida.',
			Error_InvalidEnterprise: 'Erro! Empresa Inválida.',
			Error_InvalidDate: 'Data inválida',
			Error_InvalidDepositor: 'Depositante Inválido',
			Error_InvalidInventoryType: 'Tipo de inventário inválido.',
			Error_InvalidMatchingCountConfigs: 'É necessário informar um mínimo de contagens que devem se repetir para uma contagem não ser considerada divergente.',
			Error_InvalidMinimumItemCount: 'Quantiade de contagens inválida.',
			Error_MatchingCountMustBeInformedWhenAboveOne: 'É necessário informar a quantidade de contagens válidas quando a quantidade de contagens mínimas for maior que 1.',
			Error_ThereIsAnOpenInventoryAlready: 'Já existe um inventário aberto, cancele-o ou feche-o antes de continuar.',
			Error_CantDeleteFinishedInventories: 'Não é possível excluir inventários já encerrados.',
			Error_ManifestAlreadyChecked: 'Manifesto já conferido.',
			Error_FoundDivergencesInManifestChecking: 'Encontradas divergências na conferência do manifesto.',
			AddressLabels: 'Etiquetas de Endereços',
			ProductType: 'Tipo de Produto',
			AddressStructureType: 'Tipo de Estrutura',
			ERPAddress: 'Endereço ERP',
			DefaultStorageStructureType: 'Estrutura de Armazenagem Padrão',
			Error_InvalidAddressStructureType: 'Tipo de Estrutura inválida.',
			ClosedPallet: 'Palet Fechado',
			DaysDrivein: 'Dias para Drive-In',
			CancelInternation: 'Cancelar Internação',
			TotalAmmount: 'Qtd. Total',
			ProductByLot: 'Produto Por Lote',
			AmmountInPallet: 'Qt. por Pallet',
			Error_PalletUnitNotFoundForTheProduct: 'SKU com unidade "Palete" não cadastrado para o produto: {0} - {1}.',
			Error_SkuForSelectedUnitNotRegistered: 'Sku não encontrado para a unidade selecionada do produto.',
			Error_UnitInOrderNotRecognizedForProduct: 'A unidade {0}-{3} não foi reconhecida como unidade válida para o produto {1}-{2}. Efetue o cadastro de um SKU que relacione a unidade informada com o produto.',
			MasterAmmount: 'Qt. Master',
			UnitAmmount: 'Qt. Unidades',
			ReceiptProduction: 'Recebimento da Produção',
			Confirm: 'Confirmar',
			Erro_InvalideSMU: 'Erro! UMA Invalido',
			Erro_NotEcxistThisEntry: 'Erro! Essa entrada não existe',
			Erro_ProductNotConferWithPalletVerifyLabel: 'Erro! Produto não confere com o do Palete. Verificar a etiqueta',
			PalletAmmount: 'Qt. Pallet',
			Error_SMUNotFound: 'UMA não encontrada.',
			Error_SMUAlreadyDispatched: 'A UMA informada já foi utilizada em outro processo de conferência.',
			Error_OrderUnitDoesntPairWithProductSalesUnit: 'Erro! A unidade de venda do pedido é diferente da unidade de venda cadastrada no produto.',
			Error_SalesUnitNotRegisteredForTheProduct: 'SKU de Unidade de venda não cadastrado para o produto {0}.',
			ProductOrSmu: 'Produto/UMA',
			ManifestDate: 'Data do Manifesto',
			Erro_InvalidSKU: 'Erro! SKU Invalido',
			Erro_ProductDoesNotMatchWithEntry: 'Erro! Produto não é igual ao da Entrada.',
			Error_ProductNotFound: 'Produto não encontrado.',
			SMURealocation: 'Movimentação de UMA',
			StockMovementType: 'Tipo de Movimento',
			Move: 'Movimentar',
			Error_InvalidStockMovementType: 'Tipo de Movimento inválido.',
			Error_EntryAlreadyUsedInConferenceProcess: 'Erro! Essa Entrada já foi usada em um processo de conferência.',
			PickingSupply: 'Ressuprimento do Picking',
			Erro_EntryAlreadyMoveToPicking: 'Erro! Entrada já foi movida para o picking',
			SMU: 'UMA',
			Error_SMUAlreadyMoved: 'UMA já movimentada.',
			PendingTransfers: 'Transferências Pendentes',
			Erro_TheReportedAmountExceedsTheOrderQuantity: 'A quantidade informada excede a quantidade do pedido.',
			Error_TheInformedSmuIsntInternedYet: 'AUMA informada ainda não foi internada. Por favor conclua o processo de internação.',
			Error_SmuCanceled: 'A UMA foi cancelada.',
			ConfirmInternation: 'Tem certeza que deseja realizar a internação dos itens selecionados?',
			ConfirmInternationCancellation: 'Tem certeza que deseja cancelar esta internação?',
			ConfirmLabelPrinting: 'Tem certeza que deseja imprimir as etiquetas?',
			DriveInStorageType: 'Drive-In',
			PalletStorageType: 'Porta-Palete',
			SelectAnInventory: 'Selecione um inventário',
			UnselectedAddressesMustHaveStructureSelected: 'Alguns itens não possuem endereço selecionado e deverão ser internados automaticamente. Selecione uma estrutura de endereços para estes itens.',
			ThereAreNoMoreStorageAddresses: 'Não há mais endereços disponíveis para a internação automática.',
			Error_SmuIsntInternedYet: 'A UMA informada ainda não foi recebida ou não foi internada.',
			Error_MissingSkuForSalesUnit: 'SKU não cadastrado para a unidade de venda do produto.',
			Error_SmuAlreadyInterned: 'Esta UMA já está internada.',
			Error_SkuNotFound: 'Sku não cadastrado.',
			Error_ProductNotContainsSalesUnit: 'Erro! Produto não possui unidade de venda.',
			PickingLabels: 'Etiquetas de Picking',
			InventoryConfiguration: 'Configuração de Inventário',
			Inventories: 'Inventários',
			Canceled: 'Cancelado',
			FinishingDate: 'Dt. Conclusão',
			InventoryType: 'Tipo',
			MatchingItemCount: 'Qt. de Acertos',
			MinimumItemCount: 'Mín. de Contagens',
			StartingDate: 'Data Início',
			AddressConfig: 'Configuração de Endereços',
			DepositorConfig: 'Configuração de Depositantes',
			ProductConfig: 'Configuração de Produtos',
			WarehouseConfig: 'Configuração de Depósitos',
			UserConfig: 'Configuração de Usuários',
			AreYouSureToCancel: 'Tem certeza que deseja cancelar este registro?',
			Confirmation: 'Confirmação',
			InventoryAlreadyCanceled: 'Inventário já cancelado',
			NoOpenInventoriesFound: 'Não foi localizado nenhum inventário aberto.',
			ProductAlreadyConfigured: 'Produto já configurado.',
			InformationAddress: 'Informações do Endereço.',
			Erro_AddressNotConferWithPalletVerifyLabel: 'Erro! Endereço não confere com o do Pallet.',
			Error_AddressAllocationInvalid: 'Erro! Endereço de Alocação Inválido.',
			WaitingInternation: 'Esperando Internação',
			AddressesAndUsers: 'Endereços e Usuários',
			CountNumber: 'Contagem',
			Error_InvalidCountNumber: 'Contagem inválida',
			Refresh: 'Atualizar',
			InventoryItemCount: 'Contagem de Inventário',
			FinalLevel: 'Nível Final',
			InitialLevel: 'Nível Inicial',
			FinalApartment: 'Apto. Final',
			InitialApartment: 'Apto. Inicial',
			EditUser: 'Editar Usuário',
			RemoveUser: 'Remover Usuário',
			SelectAll: 'Selecionar Tudo',
			UnSelectAll: 'Desmarcar Tudo',
			AddressNotConfiguredForInventory: 'Endereço não configurado para este inventário.',
			ProductNotConfiguredForInventory: 'Produto não configurado para o inventário.',
			AddressNotFound: 'Endereço não encontrado.',
			ProductNotFound: 'Produto não encontrado',
			InventoryAlreadyFinished: 'O inventário já foi fechado.',
			InvalidLot: 'Lote inválido',
			StockByProduct: 'Estoque por Produto',
			InventoryItemCountGuided: 'Contagem Dirigida Automaticamente',
			NoAddressesConfiguredForCurrentUser: 'Nenhum endereço configurado para o usuário logado.',
			Both: 'Ambos',
			Left: 'Esquerdo',
			Right: 'Direito',
			Any: 'Qualquer',
			StorageAddress: 'Armazenagem',
			Error_CantCheckCanceledOrder: 'O pedido está cancelado ou reprogramado e não pode ser conferido.',
			Error_ThereAreCanceledOrdersOnThisManifest: 'O manifesto não pode ser conferido, há pedidos reprogramados ou cancelados.',
			ReportForCount: 'Relatório para Contagem',
			AddressCode: 'Cód. Endereço',
			QtMaster: 'Qt. Master',
			QtUnit: 'Qt. Unidade',
			AddressWhitoutCount: 'Endereço Sem Contagem',
			RecoverPassword: 'Recuperar Senha',
			PasswordRecovery: 'Recuperação de Senha',
			PleaseResetYourPasswordByClickingHere: 'Por favor, redefinir sua senha clicando aqui',
			NotTypedPasswords: 'Senhas não digitadas',
			PasswordsDoNotMatch: 'Senhas não são iguais',
			DaysQuarantine: 'Dias de Quarentena',
			Error_EmailAlreadyRegistred: 'Erro! Email Já Cadastrado.',
			IternedItemsCanNotBeCanceled: 'Itens Internados não pode ser cancelada',
			ThisItemIsNowCanceled: 'Esse Item já está cancelado',
			Error_AddressCanNotBeBlockedBecauseThereIsProductThatAddress: 'Endereço não pode ser bloqueado pois existe produto neste endereço.',
			Released: 'Liberado',
			Blocked: 'Bloqueado',
			Error_ThisAddressNotDeleted: 'Erro! Este endereço não pode ser deletado.',
			HasRestrictionAddress: 'Possui Restriçao de Endereço?',
			AdressType: 'Tipo de Endereço',
			DaysWithoutMove: 'Dias Sem Movimentação',
			DaysToMaturity: 'Dias para Vencimento',
			PickingSupplyOrderService: 'OS de Abastecimento',
			InventoryParameters: 'Parâmetros do Inventário',
			Core_Inventory_ExpirationDate_DefaultHint: 'Sugestão de validade',
			Core_Inventory_Lot_DefaultHint: 'Sugestão de lote',
			Error_BasicUnitNotEcxist: 'Erro! Unidade Basica não existe',
			Error_InvalidLifeCycle: 'Erro! Vida Util Inválido',
			Error_InvalidShelfLife: 'Erro! Shelf Life Inválido',
			Error_PurchaseUnitNotEcxist: 'Erro! Unidade de Compra não existe',
			Error_StorageGroupNotEcxist: 'Erro! Grupo de Armazenagem não existe',
			Error_StorageUnitNotEcxist: 'Erro! Unidade de Armazenamento não existe',
			Error_InvalidMaxStorageLevel: 'Erro! Nível maximo de armazenagem inválido',
			Erro_ProductTypeNotExist: 'Erro! Tipo do Produto não existe',
			Error_InvalidClosedPallet: 'Erro! Pallet Fechado Inválido',
			Error_InvalidDefaultWeight: 'Erro! Peso Padrão Inválido',
			Error_InvalidExpirationControl: 'Erro! Controla Validade Inválido',
			Error_InvalidLotControl: 'Erro! Controla Lote Inválido',
			Error_InvalidBallast: 'Erro! Lastro Inválido',
			Error_SalesUnitNotEcxist: 'Erro! Unidade de venda não existe',
			Error_InvalidMaxStack: 'Erro! Altura Máxima do Palete inválida',
			ProductLogisticData: 'Dados Logísiticos do Produto',
			SKUForProducts: 'SKU dos Produtos',
			StockByLotAndExpirationDate: 'Estoque por Lote e Data de Validade',
			Error_AddressNotEcxist: 'Erro! Endereço não existe.',
			Error_AnotherProductInThisPickingAddress: 'Erro! Outro Produto já está cadastrado nesse endereço de Picking.',
			Error_InvalidRefillAmmount: 'Erro! Ressuprimento Inválido',
			ProductPicking: 'Picking dos Produtos',
			Error_InvalidAddressOrNotSelected: 'Endereço inválido ou nao selecionado.',
			Error_AddressUserCountAlreadyConfigured: 'O endereço {0} já possui vínculo de usuário para a contagem {1}.',
			Error_AddressAlreadyChecked: 'Alteração proibida! O endereço {0} já foi contado.',
			Error_AddressConfiguredForUser: 'Aleração proibida! O endereço {0} está configurado para um usuário efetuar a contagem.',
			Error_AddressUserCountCombinationAlreadyChecked: 'Alteração proibida! O endereço [0} já foi contado pelo usuário {1} na sequência {2}.',
			PrintLabelsForSKUBox: 'Imprimir Etiqueta do SKU de Caixa',
			PrintLabelsForSKUUnit: 'Imprimir Etiqueta do SKU de unidade',
			FinalizeInventory: 'Finalizar inventário.',
			Error_ASelectedItemWasAlreadyFullyAdmitted: 'Um item selecionado já foi completamente internado.',
			Error_ThisAddressIsPickingAndAnotherProduct: 'Erro! Este endereço é de picking e pertence a outro produto',
			Error_ThereProductWithLowerExpiryDate: 'Erro! Existe o produto com data de validade inferior',
			Error_ProductNotHavePicking: 'Erro! Produto não tem picking.',
			CreateOS: 'Criar OS\'s',
			GenerateOrderServiceForManifest: 'Criação de OS do manifesto',
			ItensQuantity: 'Quantidade de Itens',
			OrderService: 'OS',
			Error_PleaseSupplyManifestNumber: 'Informe o número do manifesto!',
			Error_OrderOfThisManifestNotContainItens: 'Erro! Os Pedidos dessa Manifesto não contem Item',
			Error_ThisManifestNotContainOrder: 'Erro! Esse Manifesto não contem pedidos',
			DynamicSupply: 'Ressuprimento Dinâmico',
			Kind: 'Tipo',
			BasicA: 'Básica',
			PlannedA: 'Planejada',
			Waved: 'Em Ondas',
			BasicSupply: 'Abastecimento Básico',
			PlannedSupply: 'Abastecimento Planejado',
			WavedSupply: 'Abastecimento em Ondas',
			ServiceOrders: 'Ordens de Serviço',
			Add: 'Adicionar',
			OrderServiceItems: 'Itens da Ordem de Serviço',
			OrderServices: 'Ordens de Serviço',
			RegisterDate: 'Dt. Registro',
			OrderServiceStatus: 'Status',
			AddPickings: 'Adicionar Pickings',
			Supplies: 'Suprimentos',
			Generate: 'Gerar',
			DetailOS: 'Detalhes da OS',
			Error_QuantitiItemNotNullOrZero: 'Erro! Quantidade de itens nula ou zero',
			Error_SupplyAnOrderNumber: 'Informe o número do pedido',
			InsuficientStockForPickingSupply: 'Estoque insuficiente.',
			Observation: 'Observação',
			PrintOS: 'Imprimir ordem de serviço',
			Error_FoundDivergencesInOrderChecking: 'Encontradas divergências na conferência do pedido.',
			DeleteAllUponSaving: 'Ao salvar, todos os itens salvos anteriormente serão excluídos e substituídos pelos novos.',
			PickingSupplyItemsSavingConfirmation: 'Os itens com falha serão ignorados. Os itens salvos anteriormente serão excluídos e substituidos pelos itens da seleção atual. Deseja continuar?',
			NoItemSaved: 'Nenhum item foi salvo.',
			ItemIsUnderAnotherOrderService: 'O item selecionado é parte de outra ordem de serviço e não pode ser alocado.',
			Error_OsCantBeUpdatedDueToFinishTimeAlreadySet: 'A OS não pode ser alterada, pois já foi finalizada.',
			OrderServiceChecking: 'Checagem da Ordem de serviço',
			StartOrderService: 'Iniciar ordem de serviço',
			AreYouSureToCancelThisOrderService: 'Tem certeza que deseja cancelar essa ordem de serviço?',
			TheOrderServiceHasNoItems: 'A ordem de serviço não possui itens!',
			TheOrderServiceIsAlreadyFinished: 'A ordem de serviço já foi finalizada!',
			TheOrderServiceIsAlreadyStarted: 'A ordem de serviço já foi iniciada!',
			TheOrderServiceIsCanceled: 'A ordem de serviço está cancelada!',
			OrderServicePickingSupplyPlacement: 'Baixa de Ordem de Serviço de Abastecimento',
			TheOrderServiceIsBeingExecutedByAnotherUser: 'A ordem de serviço está sendo executada por outro operador.',
			RemainingAmmount: 'Restante',
			TheOrderServiceWasNotFound: 'A ordem de serviço não foi localizada!',
			AreYouSureToRessupplyThisItem: 'Tem certeza que deseja ressuprir os itens selecionados?',
			TheSelectedItemsWillBeRolledBackButWontReturnToStorage: 'Os itens serão cancelados sem retorno ao endereço de armazenagem. Por favor especifique o motivo do cancelamento.',
			AreYouSureToCancelThisItem: 'Tem certeza que deseja cancelar este item?',
			Breakdown: 'Avaria',
			MissingStock: 'Estoque Inexistente',
			OneOfSelectedItemsWasAlreadyConfirmedOrCanceled: 'Um dos itens selecionados já foi confirmado ou cancelado.',
			AreYouSureToFinishThisOrderService: 'Tem certeza que deseja finalizar esta ordem de serviço? Ao cancelar essa ordem serviço, todas as outras ordens de serviço relacionadas serão canceladas. Deseja continuar?',
			OrderServiceStillHasItemsToCheck: 'Esta ordem de serviço ainda possui itens a serem verificados.',
			TheOrderServiceHasItemsPendingCheck: 'A Ordem de Serviço ainda possui itens pendentes de verificação.',
			OrderServicePickingSupplyAssociation: 'Associação de OS ao Usuário',
			AddEdit: 'Adicionar/Editar',
			OrderServiceNotFound: 'OS não localizada!',
			AreYouSureToCreateAnOrderService: 'Tem certeza que deseja criar uma ordem de serviço?',
			Stacker: 'Empilhador',
			Icon_Ok: '<i title="Ok" class="glyphicon glyphicon-ok" style="color:green"></i>',
			Icon_Pending: '<i title="Pendente"  class="glyphicon glyphicon-question-sign" style="color:black"></i>',
			Error_OrderServiceAlreadyChecked: 'Erro! OS já foi conferida.',
			OS: 'OS',
			OSCheckingByManifest: 'Conferência de OS por manifesto',
			TotalResult: 'Total de Resultados',
			Error_UserNotEcxist: 'Erro! Usuário não existe',
			Error_ProductDoesntExistOnThisOS: 'Erro! O produto não existe nessa OS.',
			InventoryImport: 'Importação de Inventário',
			FileValidate: 'Validar Arquivo',
			InvalidFile: 'Arquivo Inválido',
			ErrorInLine: 'Erro na Linha',
			IncorretColumnCountExpectedNine: 'Quantidade de colunas esperadas: 9',
			AmmountInBoxes: 'Qt. em Caixas',
			AmmountInUnities: 'Qt. em Unidades',
			ExpirationDateIsRequiredOrIsIncorrect: 'A data de validade está com o formato incorreto ou não foi informada.',
			IncorrectDataFormatExpectedDoubleForBoxAmmount: 'Quantidade em caixas com o formato incorreto, esperado número decimal separado por vírgula.',
			IncorrectDataFormatExpectedDoubleForUnitAmmount: 'Quantidade em unidades com o formato incorreto, esperado número decimal separado por vírgula.',
			IncorrectDataFormatExpectedIntegerForAddressCode: 'Código do endereço com formato incorreto. Esperado número inteiro.',
			IncorrectDataFormatExpectedIntegerForCount: 'Contagem com formato incorreto. Esperado número inteiro.',
			LotIsRequiredForProduct: 'O lote deve ser informado para o produto ou está com o formato incorreto.',
			SkuNotFoundForBasicUnit: 'Oproduto não possui configuração para o SKUde unidade básica ou mínima.',
			SkuNotFoundForBoxUnit: 'SKU de Código de Barras não cadastrado para unidade de armazenagem.',
			Error_MissingItemsToBeChecked: 'Erro! Está faltando itens para serem conferidos.',
			Erro_AmmountGreatThanTheRequest: 'Erro! Quantidade maior que a do pedido.',
			Error_ManifestAlreadyCheckedOrInChecking: 'Erro! Manifesto já foi checado ou está em checagem.',
			Error_OrderServiceDoesNotExist: 'Erro! OS não existe',
			Error_OrderServiceDoesNotExisteOnThisManifest: 'Erro! OS não existe nesse manifesto',
			Error_SkuDoesNotEcxist: 'Erro! Este SKU não existe',
			Error_NoTransferForOtherPickingAddressForOtherProduct: 'Erro! Não pode transferir para um endereço de picking de outro produto.',
			PickingCapacityIsReached: 'Capacidade do picking já foi suprida.',
			PickingCapacityIsAtLimit: 'Picking cheio, sem necessidade de abastecimento.',
			Error_EnterpriseNotRegister: 'Erro! Empresa não registrada.',
			YouAreSureToMoveThis: 'Tem certeza que deseja mover?',
			SkuNotFoundForSaleUnit: 'Sem SKU de picking.',
			Error_PickingAddressNotFoundForProduct: 'Erro! Picking não encontrado para o produto',
			ManifestDoesntHaveItems: 'O Manifesto informado não possui pedido associado, ou itens.',
			Error_InvalidDestinationAddress: 'Endereço destino inválido.',
			CantMoveFromPickingToAnotherAddressYetTryAgainLater: 'A movimentação a partir do picking para outro endereço está desabilitada.',
			InvalidManifest: 'Manifesto inválido.',
			ManifestNotFound: 'Manifesto não localizado.',
			OrderServiceAlreadyFinished: 'Ordem de Serviço já concluída.',
			OrderServiceAlreadyStarted: 'Ordem de Serviço já iniciada e não pode ser alterada.',
			ManifestAlreadyInUseByAnotherOrderService: 'O Manifesto já está em uso por outra Ordem de Serviço.',
			Analyse: 'Analisar',
			NoPickingFoundForTheProduct: 'Não foi localizado picking para o produto {0}-{1}.',
			RecordAlreadyDeleted: 'Registro já excluído.',
			ThereIsNoManifestAssociatedWithThisOrderService: 'Não há nenhum manifesto associado à esta ordem de serviço.',
			NoSaleSkuFoundForTheProduct: 'Não foi localizado SKU de unidade de venda para o produto {0}-{1}.',
			PickingNotRegistered: 'Picking não cadastrado.',
			SkuNotFoundForStorageUnit: 'Sem SKU de armazenagem.',
			OrderServicePickingSupplyBasic: 'OS de Abastecimento Básico',
			OrderServicePickingSupplyPlanned: 'OS de Abastecimento Planejado',
			OrderServiceCanceled: 'Ordem de Serviço cancelada!',
			Error_HaveOneFinishedDevolutionForThisOrder: 'Erro! Já existe uma devolução finalizada para esse pedido',
			OrderDevolution: 'Pedido de Devolução',
			AreYouSureToGenerateDevolution: 'Tem certeza que deseja gerar a devolução?',
			OrderServiceCantBeCanceledBecauseItsStarted: 'A Orderm de Serviço não pode ser cancelada, pois o manifesto já foi conferido ou está em um processo de conferência.',
			Version: 'Versão',
			Vers: 'Version',
			NoFinishDevolutionNoContainsItems: 'Não pode finalizar uma divergencia sem items',
			AreYouSureToGenerateDevolutionWithDivergence: 'Tem certeza que deseja gerar uma devolução com divergencia?',
			PartialDevolution: 'DEVOLUÇÃO PARCIAL',
			TotalDevolution: 'DEVOLUÇÃO TOTAL',
			PrintDevolutionMap: 'Imprimir Mapa de Devolução',
			PrintOrderSale: 'Imprimir Pedido de Venda',
			PrintOrderDevolution: 'Imprimir Pedido de Devolução',
			Finished: 'Finalizada',
			NotStarted: 'Não Iniciada',
			Started: 'Iniciada',
			Suspended: 'Suspensa',
			Error_NotCreateOSForThisManifestOrManifestNotEcxist: 'Erro! Não foi criada OS para esse manifesto ou esse manifesto não existe',
			Running: 'Em execução',
			ManifestDoesntHaveDevolutionItems: 'O manifesto não contem itens de devolução.',
			DevolutionByManifest: 'Devolução por Manifesto',
			PickingTransfer: 'Transferência do Picking',
			CantUseStorageAddressOnThisRoutine: 'Não é possível efetuar transferência de endereços de armazenagem.',
			InsuficientStockForTransfer: 'Estoque insuficiente para transferência.',
			InvalidDestinationAddress: 'Endereço destino inválido!',
			InvalidOriginalAddress: 'Endereço de origem inválido!',
			NegativeAmmountInformed: 'Informada quantidade negativa.',
			SupplyIsNotNeeded: 'Sem necessidade de abastecimento.',
			Icon_NotOk: '<i title="Verificado com erro!"  class="glyphicon glyphicon-exclamation-sign" style="color:red"></i>',
			Error_ThisAddressBlocked: 'Erro! Esse endereço está bloqueado.',
			Error_InsufficientAddressForThisInternation: 'Erro! Endereços insuficientes para internação.',
			Error_ProductHeightInvalid: 'Erro! Altura do produto inválida.',
			AreYouSureToPrintVolumeLabel: 'Você deseja imprimir as etiqutas de volume?',
			HowManyVolumesGenerated: 'Quantos volumes foram gerados?',
			Process: 'Processo',
			InternalMoviment: 'Movimentação Interna',
			ItensPerPage: 'Itens por pagina',
			VolumeLabel: 'Etiqueta de Volume',
			PrintDate: 'Dt. da Impressão',
			FinishSeparation: 'Finalizar Separação',
			SeparationFinishDate: 'Fim da Separação',
			SeparationStartDate: 'Início da Separação',
			StartSeparation: 'Iniciar Separação',
			SeparationAlreadyFinished: 'Separação já finalizada!',
			Error_OrderWasntSeparatedYet: 'Não há separação para o pedido ou a separação ainda não foi finalizada.',
			IntegrationCode: 'Código de Integração',
			SeparationMapPrintDate: 'Dt. Impressão',
			SeparationMapSerial: 'Versão',
			Matriculation: 'Matrícula',
			OrderNotFound: 'Pedido não encontrado.',
			SeparatorAlocation: 'Alocação de Separadores',
			Error_SelectASeparator: 'Selecione um separador.',
			TheOrderIsAlreadyAllocatedToAnotherSeparator: 'O pedido já está alocado para outro separador, tem certeza que deseja efetuar a realocação para o separador selecionado?',
			Error_InvalidOrder: 'Pedido Inválido',
			Error_InvalidSeparator: 'Separador inválido.',
			CancelAllocation: 'Cancelar Alocação',
			ConfirmSeparation: 'Confirmar Separação',
			AreYouSureToCancelTheSelectedAllocations: 'Tem certeza que deseja cancelar todas as alocações selecionadas?',
			AreYouSureToReportTheSeparationFinish: 'Tem certeza que deseja confirmar a separação de todos os pedidos selecionados?',
			CheckerCode: 'Cód. Conferente',
			CustomerCode: 'Cód. Cliente',
			SeparatorCode: 'Cód. Separador',
			NotPrinted: 'Não Impressos',
			NotSeparated: 'Não Separados',
			Printed: 'Impressos',
			PrintStatus: 'Status da Impressão',
			RowsPerPage: 'Registros por Página',
			Separated: 'Separados',
			SeparationStatus: 'Status da Separação',
			TotalRecords: 'Total de Registros',
			ReportProductivityBySeparator: 'Relátorio de Produtividade por Separador',
			AmmountItems: 'Qtd. Itens',
			AmmountOrder: 'Qtd. Pedidos',
			ItemsPerMinute: 'Itens/Minuto',
			Sequential: 'Sequencial',
			TotalTime: 'Tempo Total',
			ReportProductivityByChecker: 'Relatório de Produtividade por Conferente',
			ProductGroup: 'Grupo do Produto',
			ProductGroupMaintenance: 'Manutenção Groupo do Produto',
			SkuNotFoundForPurchaseUnit: 'SKU não encontrado para a Unidade de entrada.',
			ChangeVolume: 'Mudar Volume',
			PrintAllLabels: 'Imprimir Todas as Etiquetas',
			PrintExpecficLabel: 'Imprimir etiqueta específica',
			YouAreSureToPrintAllLabels: 'Tem certeza que deseja imprimir todas as etiquetas?',
			PrintIntervalLabel: 'Imprimir Intervalo de etiquetas',
			Error_ThisBarCodeRegistred: 'Código de barra já cadastrado',
			Error_BasicUnitNotRegisteredForTheProduct: 'Erro! Unidade básica sem SKU associado para o produto.',
			Error_OrderIsPendingOrCanceled: 'Erro! O pedido está pendente ou cancelado.',
			Error_OrderNotSaparete: 'Erro! Separação do pedido não finalizada.',
			TotalOrder: 'Total de Pedidos',
			Error_BasicSkuNotFoundForTheProduct: 'SKU de unidade básica não cadastrado para o produto {0} - {1}.',
			Error_SalesSkuNotFoundForTheProduct: 'Produto sem SKU de picking {0} - {1}.',
			AllowBarCodeNull: 'Permitir código de barra vazio?',
			Yield: 'Rendimento',
			Error_OrderServiceAlreadySepared: 'Erro! OS já foi separada',
			OrderServiceSeparation: 'Separação da OS',
			Error_InventoryTypeCantBeChanged: 'O tipo de inventário não pode ser modificado.',
			Error_TheInventoryIsAlreadyFinished: 'O inventário já foi finalizado.',
			AmmountGreatThanInAddress: 'Quantidade maior que a do endereço.',
			EcxistAmmountReservedForOrderServiceSupplyPicking: 'Existe {0} quantidades reservadas para o resuprimento do picking',
			ConfirmAddressEmpty: 'Confirma endereço vazio?',
			Error_HaveGeralInventoryOpen: 'Existe um inventário geral aberto',
			Error_HaveParcialInventoryOpen: 'Existe um inventário parcial aberto',
			FirstCountAutomaticForPicking: '1ª contagem automática para picking',
			FirstCountAutomaticForStorage: '1ª contagem automática para armazenagem',
			CountingDivergence: 'Divergência de contagem',
			Counts: 'Contagens',
			YouAreSureToFinishThisInventory: 'Você tem certeza que deseja finalizar esse inventário?',
			Error_NotDeletePickingThisHaveAmmount: 'Erro! Picking não pode ser deletado antes de ser zerado.',
			TranferPicking: 'Tranferência de picking',
			OrderDate: 'Data Pedido',
			Segregated: 'Segregado',
			PickingNotRegisteredForProduct: 'Picking não cadastrado para o produto ',
			SeparationNotStarted: 'Separação não iniciada',
			InvalidIntervalOrNull: 'Intervalo inválido ou não informado.',
			PickingWithoutSupply: 'Picking sem necessidade de abastecimento.',
			QueryNegativePickings: 'Consulta de pickings negativos',
			CodeAddress: 'Cod. Endereço',
			FoundMoreThanOneSKUPallet: 'Encontrado mais de um sku de pallet',
			FoundMoreThanOneSKUStorage: 'Encontrado mais de um SKU de armazenagem',
			FoundMoreThanOneSKUUnit: 'Encontrado mais de um SKU de unidade basica',
			Error_NotRegistredSalesUnit: 'Erro! Não foi registrado unidade de compra',
			Error_NotRegistredStorageUnit: 'Erro! Não foi registrado unidade de armazenagem',
			Print: 'Imprimir',
			ListAdress: 'Listar endereços',
			ArcheiveDownload: 'Baixar arquivo',
			OrderCheckSuccessFull: 'Pedido conferido com sucesso',
			GenerateReturn: 'Gerar retorno',
			RefreshDate: 'Zerar dados',
			ShowItens: 'Mostrar itens',
			FinishConference: 'Finalizar conferência',
			Expand: 'Expandir',
			Check: 'Checar',
			StorageSKU: 'SKU Armazenagem',
			InventoryCanceled: 'Inventário cancelado',
			InventoryNotFound: 'Invantário não encontrado',
			YouAreSureToPrintLabel: 'Tem certeza que deseja imprimir esta etiqueta?',
			SlsUnit: 'Und. Venda',
			GenerateInventory: 'Gerar inventário',
			YouAreSureToCreateInventoryForAllNegativePicking: 'Tem certeza que deseja criar um inventário para todos os endereços de picking negativo?',
			NotLoggedUser: 'Usuário não está logado.',
			AddAddress: 'Adicionar Endereço',
			DeleteAddress: 'Deletar Endereço',
			YouAreSureToDeleteThisAddress: 'Você tem certeza que deseja deletar esse endereço?',
			PleaseSelectAddressPicking: 'Selecione um endereço de picking',
			InventoryHasBeenCanceled: 'Este inventário está cancelado',
			InventoryHasBeenFinished: 'Inventário já foi finalizado',
			Error_UserInactive: 'Erro! Usuário está inativo',
			ServicesMaintenance: 'Manutenção de Serviços',
			Services: 'Serviços',
			ConferenceStatus: 'Status da Conferência',
			InConference: 'Em Conferência',
			InSeparation: 'Em Separação',
			RunningProcess: 'Processo em andamento',
			NewService: 'Novo Serviço',
			Error_DescriptionUnknown: 'Descrição não informada!',
			NoConfigAddressForInventoryByDepositor: 'Não pode configurar endereços para um inventário por depositante',
			NoConfigAddressForInventoryByProduct: 'Não pode configurar endereços para um inventário por produto',
			NoConfigProductForInventoryByAddress: 'Não pode configurar produtos para um inventário por endereço',
			NoConfigProductForInventoryByDepositor: 'Não pode configurar produtos para um inventário por deposito',
			Table: 'Tabela',
			PriceTable: 'Tabela de Preços',
			NewTable: 'Nova Tabela',
			Ressuply: 'Ressuprimento',
			Error_InactiveSeparator: 'Erro! Separador Inativo. ',
			Error_ServiceNotSelected: 'Serviço não selecionado!',
			CodDocument: 'Cod. Documento',
			PreviousAmmount: 'Qt. Anterior',
			FinishOrderServicePickingSupply: 'Finalizar ordem de serviço de abastecimento!',
			ThereIsStillOutstandingItems: 'Ainda existem itens pendentes',
			NegativePickingCount: 'Contagem de picking negativo.',
			AmmountERP: 'Quantidade ERP',
			AmmountWMS: 'Quantidade WMS',
			UnitERP: 'Unidade ERP',
			UnitWMS: 'Unidade WMS',
			ProductDoenstHaveNegativePicking: 'Este produto não possui picking negativo.',
			Error_ProductHasNotUnit: 'Produto não possui unidade cadastrada.',
			DetailBlindNote: 'Detalhamento da Nota Cega',
			PrintBlindNote: 'Imprimir Nota Cega',
			AreYouSureToCancelThisBlindNote: 'Você tem certeza que deseja cancelar essa Nota Cega ?',
			BlindNoteDate: 'Data da Nota Cega',
			RequestWithBlindNote: 'Existem notas de entrada com nota cega associada.',
			AddToBlindNote: 'Adicionar para lista de notas',
			WithOutBlindNote: 'Sem nota cega',
			Error_BlindNoteAlreadyFinished: 'Nota cega já foi finalizada.',
			Error_ProductDoesntExistOnThisBlindNote: 'Produto não existe nessa nota cega.',
			BlindNoteCheckNotFound: 'Nota cega não encontrada.',
			RequestToBlindNote: 'Notas para Nota Cega',
			PrintBlindNoteDivergence: 'Imprimir Divergências da Nota Cega',
			Completed: 'Completada',
			OnExecution: 'Em Execução',
			NoPalletization: 'Sem Paletizacao',
			BlindNoteAlreadyChecked: 'Espelho já conferido.',
			BlindNoteSuccessChecked: 'Espelho conferida com sucesso!',
			DivergencesBlindNote: 'Encontradas divergências na conferência da nota cega.',
			StartedConferenceBlindNote: 'Iniciada a conferencia do espelho.',
			TotalRecebimento: 'Total Recebimento',
			WithBlindNote: 'Com nota cega',
			BlindNoteWithOutDivergenceOrFinished: 'Nota cega não possui divergências ou já finalizada.',
			AmmountConfered: 'Quantidade Conferida',
			AuthozireDivergence: 'Autorizar Divergencia',
			ItemAuthorized: 'Item autorizado com sucesso!',
			SupplierConfig: 'Configuração de Fornecedores',
			NoConfigAddressForInventoryBySupplier: 'Não pode configurar endereços para um inventário por fornecedor',
			NoConfigProductForInventoryBySupplier: 'Não pode configurar produtos para um inventário por fornecedor',
			NoConfigSupplierForInventoryByAddress: 'Não pode configurar fornecedores para um inventário por endereço',
			NoConfigSupplierForInventoryByDepositor: 'Não pode configurar fornecedores para um inventário por depositor',
			NoConfigSupplierForInventoryByProduct: 'Não pode configurar fornecedores para um inventário por produto',
			Error_VolumeNumberCantBeZero: 'O volume não pode ser 0!',
			Warn_OperationSuccessButPrinterNotFound: 'A operação foi concluída, mas houve um erro na impressão!',
			PickingType: 'Tipo de Picking',
			PickingNeedBeTheSameTypeOfDestiny: 'O tipo de picking precisa ser do mesmo tipo do de destino',
			CantMoveForTheSamePickingType: 'Não pode mover para um tipo de picking igual.',
			PickingCantNotDuplicateType: 'Já existe esse tipo de picking cadastrado',
			PickingDefaultNotFoundForThisProduct: 'Picking padrão não cadastrado para esse produto',
			CreatingWithInterval: 'Criação entre intervalos.',
			Error_DepositorNotExists: 'Erro! Depositor não existe!',
			HasLogisticOperator: 'Tem operador logístico?',
			Error_OrderNotAlocated: 'Pedido não alocado a separador',
			ApartmentInitialMustBeLowerThanApartmentNumber: 'Apartamento inicial deve ser menor que o número de apartamentos',
			ApartmentInitialMustBeMoreThanZero: 'Apartamento inicial deve ser maior que zero',
			BlockInitialMustBeLowerThanBlockNumber: 'Bloco inicial deve ser menor que o número de blocos',
			BlockInitialMustBeMoreThanZero: 'Bloco inicial deve ser maior que zero',
			Error_CouldNotCreateTheAddresses: 'Falha ao criar os endereços',
			LevelInitialMustBeLowerThanLevelNumber: 'Nível inicial deve ser m que o número de níveis',
			BoxWithVariableWeight: 'Caixas com peso variável',
			OrderImportedSuccess: 'Importada com sucesso',
			EntryDate: 'Data de entrada',
			ForkliftOperator: 'Empilhador',
			ForkliftOperatorMaintenance: 'Manutenção de Empilhadores.',
			ForkliftOperatorNotAlocateToOS: 'Empilhador não alocado para Ordem de serviço.',
			Error_UserNotAssocied: 'Não existe usuário cadastrado.',
			InvoiceDataImportXML: 'Importação dados XML NFe',
			OrderData: 'Arquivo de pedido',
			Error_OrderAllReadyImported: 'Esta nota já foi importada.',
			Error_ImportOrderFailed: 'Erro ao importar a NFe',
			RequestData: 'Arquivo de entrada',
			Error_CodeNotWritedForProduct: 'Digite um código para o produto',
			Error_SupplierNotSelected: 'Selecione um fornecedor',
			ProductSupplier: 'Código por fornecedor',
			Error_SupplierAllReadyAllocatedToProduct: 'Fornecedor já associado a esse produto',
			Error_OrderCheckingItemValidityRequired: 'Este produto precisa informar a data de validade',
			InformValidityCheck: 'Informar validade na conferência',
			ShelfLifeExpedition: 'Shelf Life de Expedição(Dias).',
			InProgress: 'Em progresso',
			PrintLateralLabels: 'Imprimir Etiquetas Laterais',
			AllowRequestItemEdit: 'Editar item na Nota de Entrada',
			ReceiptInternation: 'Recebimento da Internação',
			Error_AddressDoesntExistForThisUMA: 'Este endereço não corresponde para essa UMA',
			ProductLabel: 'Etiqueta de Produto',
			LabelsQuantity: 'Quantidade de Etiquetas',
			CreationDate: 'Data de criação',
			FinishedDate: 'Data de conclusão',
			InventoryTime: 'Tempo do inventário',
			Hours: 'Horário',
			Error_AddressAlreadyHaveDepositor: 'Erro. O endereço de destino já está reservado para outro depositante.',
			CSVOrderImport: 'CSV Arquivo de pedido',
			Error_ThisProductIsAllReadyCounted: 'Este produto já bateu contagem!',
			OrderExpedition: 'Expedição de Pedidos',
			NoRegistersWasFounded: 'Nenhum registro encontrado!',
			Error_OrderAllReadyWithManifest: 'Pedido já existe em um manifesto!',
			Error_OrderWithThisManifest: 'Este pedido já esta no manifesto!',
			Error_ThisPickingDidAllReadyGetCounted: 'Este endereço de picking já bateu contagem!',
			Devolution: 'Devolução',
			Error_ThisOrderCannotChangeVolumes: 'Este pedido não pode ter alteração nos volumes',
			GroupOrderManifestVolume: 'Agrupamento de Volume por Manifesto',
			OrderManifestVolumeItem: 'Itens do Manifesto por Volume',
			OrderVolume: 'Volume do Pedido',
			DocumentDate: 'Data do documento',
			Error_IdentifyNotFound: 'Identificador não reconhecido',
			Error_OrderVolumeAllReadyOnThisManifest: 'Volume do pedido já associado ao manifesto',
			Error_OrderVolumeInvalid: 'Volume de pedido invlálido',
			OrderVolumeIndetification: 'Volume identificador do Pedido',
			OrderServicePickingSupplyForkAssociation: 'Associação de OS ao empilhador',
			AggregateVolumes: 'Volumes agredados',
			ExpeditionConference: 'Conferência de Expedição',
			VolumeChecked: 'Volumes conferidos',
			Error_ThisManifestHasNoVolumes: 'Este manifesto não gerou volumes',
			Error_HaveNoOrderOnThisManifest: 'Não há pedidos nesse manifesto',
			Error_ManifestInCheckingProcess: 'Manifesto já está em estado de conferência',
			Error_OrderNotInManifest: 'Pedido não existe no manifesto',
			Error_OrdersPendingForCheck: 'Existem pedidos pedentes de conferência desse manifesto',
			Error_VolumeAllReadyChecked: 'Volume já conferido',
			Error_LabelManifestInvalid: 'Etiqueta de manifesto inválida',
			Error_ProductNotFoundToThisDepositor: 'Produto não encontrado para este depositante',
			CheckingProductAndDriver: 'Avaliação do Veículo/Produtos',
			DriveBoard: 'Placa do Veículo',
			FinalDischarge: 'Fim da Descarga',
			Receipt: 'Recebimento',
			ReceiptDate: 'Data de Recebimento',
			StartDischarge: 'Início da Descarga',
			ThermometerCode: 'Código do Termômetro',
			CorrectiveAction: 'Ação corretiva',
			ImmediateAction: 'Ação imediata',
			Occurrence: 'Ocorrencia',
			QualityActionInCaseOfAvoid: 'Qualidade - Ações em caso de Desvio',
			Supervisor: 'Supervisor',
			VerifyBoxTemperature: 'Medição da Temperatura do Baú',
			Hide: 'Esconder',
			Show: 'Mostrar',
			Error_OrderNumberAllReadyExist: 'Número de pedido ja existe',
			SkuUnit: 'SKU de unidade',
			Error_AddressAllReadyConfirmedAsEmptyByThisUser: 'Endereço já foi confirmado como vazio!',
			Error_OrderItemInCheckingProcess: 'Item de pedido em processo de conferência',
			Error_OrderNotFoundForThisDepositor: 'Pedido não encontrado para este depositante.',
			ClosedBoxPackage: 'Embalagem de Caixa Fechada',
			DefaultPackage: 'Embalagem Padrão',
			FabricationDate: 'Data de Fabricação',
			PulpInbar: 'Polpa em Barra',
			OrderServiceAllReadyHasSeparator: 'Esta ordem de serviço ja possui separador.',
			OrderServiceHasNotSeparator: 'Orderm de serviço não possui separador alocado',
			SKULabel: 'Etiqueta de SKU',
			Error_WriteTheProduct: 'Digite um Produto',
			Error_WriteTheSKU: 'Digite um SKU',
			Error_SkuNotFoundForThisProduct: 'Não existe nenhum SKU cadastrado para este produto.',
			Error_ProductWithoutPurchaseUnit: 'Erro! O produto está sem unidade de compra!',
			Error_SkuIsNotPurchaseUnit: 'Erro! A unidade deste SKU não é de compra!',
			Error_SkuWithoutUnit: 'Erro! O SKU está sem unidade!',
			FinishedInventory: 'Inventário Finalizado',
			ReceiptCrossDock: 'Recebimento CrossDock',
			SelectRequest: 'Selecione uma nota de entrada',
			NotChecked: 'Não conferido',
			Error_LotOrExpirationDateInvalidForOrderItem: 'Lote ou Validade não disponível para este item',
			Error_HaveMoreThanOneExpirationForThisProduct: 'Existe mais de um endereço com esta validade',
			Error_HaveMoreThanOneLotForThisProduct: 'Existe mais de um endereço com este lote',
			Brand: 'Marca',
			Color: 'Cor',
			Error_ThisProductDoesntControllGrid: 'Este produto não controla grade!',
			Size: 'Tamanho',
			Apto: 'Apto',
			NoActivities: 'Sem atividades pendentes.',
			Rotine: 'Rotina',
			SelectAnActivity: 'Selecione uma atividade',
			VolumeAddress: 'Endereço de volume',
			VolumeAssociation: 'Associação de Volumes ao Endereço',
			CrossDockingItens: 'Itens CrossDocking',
			CrossDockingLabel: 'Etiqueta de CrossDocking',
			CrossDockingAddress: 'Endereço de CrossDocking',
			Error_AmmountOnItensInsufficient: 'As quantidades dos itens ainda não estão batendo de acordo com a nota.',
			Error_ThisCrossDockingIsAlreadyOnStock: 'Este CrossDocking já gerou registros.',
			CrossDockingExpedition: 'Expedição de CrossDock',
			Error_ThisRequestItsNotCrossDocking: 'Esta nota não é de CrossDock ou não possui itens!',
			Error_VolumesWithDivergence: 'Possuem volumes divergentes!',
			ListItens: 'Listar itens',
			Sent: 'Enviada',
			NotSent: 'Não enviada',
			GroupNameAdministration: 'Administration',
			GroupNameInternation: 'Internacao',
			GroupNameSupply: 'Abastecimento',
			CantConnect: 'Não foi possível conectar, o servidor está offline.',
			Connected: 'Conectado',
			ConnectionLosted: 'Conexão perdida, tentando reconectar...',
			Reconnected: 'Re-conectado com sucesso',
			RefuseActivity: 'Recusar Atividade',
			Refused: 'Recusada',
			OpConferred: 'OP já foi conferida.',
			CheckInAddress: 'Endereço de Check-IN',
			UMA: 'UMA',
			Qtd: 'Qtd.',
			ItensAlreadyCreated: 'Itens já criados!',
			AllocationConfirmationCrossDocking: 'Confirmação de Volume CrossDocking',
			CheckListReceiptProduct: 'Check List de Recebimento',
			Temperature: 'Temperatura',
			Error_RequestHasCheckListReceipt: 'Esta entrada ja deve um Check List de Recebimento preenchido',
			Error_ManifestDidNotChecked: 'Manifesto não conferido',
			CheckListExpedition: 'Check List de Expedição',
			AccessKey: 'Chave de Acesso',
			RecoverXML: 'Recuperar XML',
			Error_AmmountInformedIsHigherThatCapacityPicking: 'A quantidade informada é superior à capacidade do Picking',
			Error_BlindNoteNotChecked: 'Não existe Nota Cega para esse nota ou não foi conferida.',
			YouAreSureDelete: 'Tem certeza que deseja excluir?',
			OriginalCount: 'Qtd. Original',
			PacketCount: 'Qtd. Reservada',
			Reserves: 'Reservas',
			KitPersonalization: 'Kit de Personalização',
			Personalization: 'Personalização',
			PersonalizationStation: 'Estação de Personalização',
			UMAValidation: 'Validação de UMA',
			UMAAlreadyAllocation: 'UMA já associada.',
			UMACreation: 'Cadastro de UMA Avulsa',
			ManualPickingSupply: 'Abastecimento Manual do Picking',
			Error_PickingInvalid: 'Picking inválido!',
			Error_HasNotAddressRealeseForThisPicking: 'Não existem endereços livres para movimentação deste picking',
			RequestedAmmount: 'Qtd Solicitada',
			AreYouSureToSkipThisUMA: 'Tem certeza que deseja pular esta UMA?',
			Filter: 'Filtro',
			Decreasing: 'Decrescente',
			Growing: 'Crescente',
			Sequence: 'Ordem',
			Error_SMUDoesntExist: 'UMA não existe no sistema',
			Error_ThisUserAllReadyCountedThisAddress: 'Este usuário já contou esta UMA neste Endereço',
			ProductGrid: 'Grade do Produto',
			ChangeAddress: 'Mudar Endereço',
			Error_AddressNeedHaveACount: 'Este endereço precisa ser contado ao menos uma vez!',
			SkipAddress: 'Pular Endereço',
			Error_AddressAllReadySkiped: 'Endereço já pulado!',
			Error_ProductAllReadyCounted: 'Este produto já bateu contagem!',
			Error_AddressWithoutPicking: 'Endereço sem Picking Cadastrado',
			Attention_AddressWithCountWillBeIgnored: 'Atenção: Endereços que já tiveram contagens serão ignorados',
			Attention_AddressWithUserWillBeIgnored: 'Atenção: Endereços com usuários associados serão ignorados',
			Error_ThereIsNoItemsToReturnToPicking: 'Não á itens para retornar ao Picking!',
			OrderServiceHasLotsOnMob: 'Este OS ainda possui lote(es) no(os) carrinho(os)',
			RemainingLots: 'Lotes Restantes',
			Error_CanNotClearAddressWithCount: 'Não pode esvaziar um endereço já contado!',
			ItensList: 'Lista de Itens',
			Error_ToCancelNeedsToBeRequested: 'Para cancelar precisa ser solicitado!',
			ItemAllReadyChecked: 'Item já conferido!',
			ThisItemGotRequestedToCancel: 'Este item foi solicitado cancelamento!',
			ConsolidationAddress: 'Endereço de consolidação',
			ExitConsolidationDate: 'Data de saída da consolidação',
			Error_HasAnotherProductOnStorage: 'Este endereço de armazenagem já esta com outro(os) produto(os)',
			ChangesReceipt: 'Recebimento de Trocas',
			AddressNotMobile: 'Endereço não é móvel.',
			MattingAddressNotFound: 'Não foi possível encontrar o endereço da esteira.',
			AddressMobileAssociated: 'Este carro móvel já esta associado em outros itens.',
			AddressNotPickingOrStorage: 'Endereço precisa ser Picking ou Armazenagem.',
			AddressReservedToMoviment: 'Endereço reservado para movimentação.',
			AddressWithoutItemsToOS: 'Este usuário não possui itens para essa OS.',
			CapacityLimit: 'Capacidade máxima já foi atingida nesse endereço.',
			DestinationMustBePickingOrStorage: 'Endereço de destino precisa ser de Picking ou Armazenagem.',
			EntryAlreadyTransfered: 'UMA já transferida.',
			EntryNotAssociated: 'UMA não associadas.',
			EntryNotFound: 'Entradas não encontradas.',
			EntryNotFoundOrNotOfActivity: 'UMA não existe, ou não pertence à essa atividade.',
			InvalidAddressToOperation: 'Endereço inválido para operação.',
			InvalidMobile: 'Endereço móvel inválido.',
			InvalidUMA: 'UMA inválida.',
			LotWithoutStock: 'Lote sem estoque.',
			ManualTransfer: 'Transferência Manual.',
			OriginalAddressCantBePicking: 'Endereço original precisa ser de armazenagem.',
			ProductIncorrectPicking: 'Produto não pertence a este Picking.',
			UMACantBeSupply: 'Esta UMA não pode abastecer, retorne para a armazenagem.',
			UMAInAddressReserved: 'Esta UMA neste endereço esta reservado para movimentação.',
			UMANotFound: 'UMA não existe no sistema.',
			UMAWithoutStockAddress: 'UMA sem endereço de estoque.',
			WithoutItemsBiped: 'Nenhum item bipado.',
			WithoutOverOP: 'Sem saldo para essa OP.',
			WithoutSalesSKU: 'sem SKU de picking!',
			WithoutStorageandSalesSKU: 'sem SKU de armazenagem e picking!',
			WithoutStorageSKU: 'sem SKU de armazenagem!',
			NoReserveToRelease: 'Nenhuma reserva para liberar.',
			OrderAlreadyReleased: 'Pedido já foi totalmente liberado.',
			InvalidUMAOrAlreadyAllocated: 'UMA inválida ou já alocada.',
			Error_ThisUserAllReadyCountedThisProduct: 'Este usuário ja contou este produto',
			EntryDateConsoloditationAddress: 'Data de Entrada na Consolidação',
			ActivityList: 'Lista de Atividades',
			ActivityManagementPanel: 'Painel de Gestão de Atividades',
			Consolidation: 'Consolidação',
			ReleaseConsolidation: 'Liberação da Consolidação',
			Priority: 'Prioridade',
			UMAInAddressReservedToOrder: 'Esta UMA neste endereço esta reservado para pedido.',
			ReservesMoreThanOriginal: 'Quantidade de reservas supera a quantidade original.',
			General: 'Geral',
			Prioritize: 'Priorizar',
			PickTheOrderWhichYouWantSwitch: 'Selecione o Pedido na qual deseja trocar a prioridade',
			TheOrdersMustBeDifferents: 'Os pedidos precisam ser diferentes',
			TotalActivitys: 'Total de Atividades',
			DesiredPriority: 'Prioridade Desejada',
			PickingAssociation: 'Validação/Associação de Picking',
			ConfirmWithAdminPassword: 'Confirme a operação com a autorização do Administrador',
			EditAmmount: 'Editar Quantidade',
			ReportSMUToChangeAmmount: 'Informe a UMA para alterar a quantidade',
			PersonalizationChecking: 'Conferência da Personalização',
			SMUAlReadyCustomized: 'UMA já foi personalizada',
			SMUNotReadyForPersonalization: 'UMA não está pronta para personalização',
			AvaliableCount: 'Qtd. Disponível',
			SMUDoesntBellongToThisActivity: 'UMA não pertence a essa atividade',
			AddressIsntPersonalizationStation: 'Endereço não corresponde a uma estação de personalização!',
			ActivityNotFound: 'Atividade não encontrada',
			Busy: 'Ocupado',
			Vacant: 'Vago',
			PersonalizationStationHasNotOrder: 'Esta estação não está configurada para nenhum pedido!',
			SMUArentOnPersonalizationAddress: 'UMA não se encontra na estação de personalização',
			SMUCostumized: 'UMAs Personalizadas',
			SMUIsGettingCheckingByAnotherUser: 'UMA está sendo personalizada por outro usuário',
			KitCreation: 'Montagem da Grade',
			TotalAvaliable: 'Total Disponível',
			TotalConsolidate: 'Total Consolidado',
			TotalPersonalizate: 'Total Personalizado',
			LotNotFound: 'Lote não encontrado.',
			FailInsertERP: 'Falha ao inserir no ERP, bipe novamente.',
			LotAlreadyConferred: 'Lote já conferido.',
			LotWithConferrenceOpenStation: 'Lote com conferência em andamento na estação: ',
			OpAlreadyAssociatedManifest: 'OP está associada à um manifesto.',
			OpNotFound: 'OP não encontrada.',
			WithoutBalance: 'Sem saldo para essa OP.',
			Station: 'Estação',
			CheckedParts: 'Peças Conferidas',
			Parts: 'Peças',
			RemainingPacks: 'Packs Restantes',
			RemainingParts: 'Peças Restantes',
			TotalPack: 'Total de Packs',
			TotalParts: 'Total de Peças',
			PersonalizedParts: 'Peças Personalizadas',
			SMUNotInMat: 'UMA não enviada para Esteira',
			StationNotReadyForPersonalization: 'A estação dessa UMA ainda não está pronta para personalizar!',
			SMUAlreadyOnPersonalizationAddress: 'UMA já esta alocada em uma estação de personalização!',
			StationAddress: 'Endereço da Estação',
			SMUNotConfiguredToPersonalization: 'UMA não solicitada para personalização',
			SMUNotReleasedToPersonalization: 'UMA não liberada para personalização',
			PacksCheckeds: 'Packs Montados',
			LotItems: 'Item do Lote',
			Error_UserIsNotAdmin: 'Este usuário não é administrador',
			ColorInPackMontage: 'Cor em Montagem de Pack',
			PersonalizationAddress: 'Endereço da Personalização',
			SMUPersonalization: 'Personalização de UMA',
			AlarmType: 'Tipo de Alarme',
			GridType: 'Tipo de Grade',
			LabelType: 'Tipo de Etiqueta',
			PackType: 'Tipo de Pack',
			PersonalizationType: 'Tipo de Personalização',
			Uninformed: 'Não Informado',
			CheckedAmmount: 'Quantidade Conferida',
			PrintPackLabel: 'Imprimir Etiqueta do Pack',
			PrintVolumeLabel: 'Imprimir Etiqueta do Volume',
			OrderSupply: 'Ordem de Abastecimento',
			PackLabel: 'Etiqueta do Pack',
			TransBetweenTransactionAddress: 'Transferência entre endereços de transição',
			WaitingRelease: 'Aguardando Liberar',
			WaitingUser: 'Aguardando Usuário',
			CancelItem: 'Cancelar Item',
			ActivityGuided: 'Atividade',
			CancelSelectedItems: 'Cancelar Selecionados',
			ItemAlreadyChecked: 'Item já foi conferido.',
			CantCancelItemConferred: 'Não é possível cancelar um item já conferido.',
			ItemAlreadyCanceled: 'Item já foi cancelado.',
			AddressReserved: 'Endereço Revervados',
			CouldNotSaveTheAddressBellow: 'Os Endereços abaixos não puderão ser salvos, pois estão configurados/reservados para outras operações',
			CouldNotSaveTheItensBellow: 'Não foi possível salvar os itens, devido a produtos com erro de dado logístico',
			ListAddressNotSaved: 'Lista dos Endereços que não serão salvos na configuração',
			ListProductWithoutSKUorSales: 'Lista dos produtos abaixo que não possuem SKU de venda ou Armazenagem',
			Reason: 'Motivo',
			AreYouSureToKeepWithOperation: 'Deseja continuar com a operação?',
			AreYouSureToSaveItenBellow: 'Deseja salvar os itens abaixo?',
			Retract_Expand: 'Retrair/Expandir',
			WaitingOrder: 'Aguardando Pedido',
			PendingActivities: 'Existem atividades que foram iniciadas e não foram finalizadas para esse usuario, favor finalizar antes de alterar o depósito.',
			BoxType: 'Tipo de Caixa',
			LabelPriceType: 'Tipo de Etiqueta Preço',
			RequestUMA: 'Solicitação de Reposição',
			InvalidPack: 'Pack Inválido',
			PackAllReadyChecked: 'Pack já Conferido',
			PackOrderNotEqualVolumeOrder: 'Pedido do Pack não corresponde ao do Volume em conferência!',
			ProductConsultation: 'Consulta de Produtos',
			ProductCodeShort: 'Cod. Produto',
			ProductTransfer: 'Transferência de Produto',
			Default: 'Padrão',
			SendCount: 'Enviar Contagem',
			ProductTransferAmongAddress: 'Transferência de Produtos entre Endereços',
			Error_UserAlreadyRegisteredInAddress: 'Usuário já associado no endereço',
			Expiration: 'Validade',
			NextAddress: 'Próximo Endereço',
			CancelRequest: 'Cancelar Nota Fiscal',
			RequestAlreadyGotInterned: 'Esta nota já possui entrada no sistema. Não pode ser cancelada.',
			ReasonNeedBeInformed: 'O motivo precisa ser informado.',
			Error_UnitAlreadyRegistredForProduct: 'Está unidade já esta cadastrada para esse produto',
			AddressMobile: 'Endereço Móvel',
			AssociateUser: 'Associar Usuário',
			Supply: 'Abastecimento',
			Transfer: 'Transferência',
			Error_AmmountDivergence: 'Quantidade Divergente',
			FinishPalletCheck: 'Finalizar Conferência do Pallet',
			DoYouWantToAllowDivergenceOfItem: 'Deseja autorizar a divergência deste item?',
			PalletAlreadyFinished: 'Palete já finalizado',
			ProductMustBeVariableWeight: 'Produto necessita ser de peso variável',
			ClickWithRigthButtonOfMousePallet: 'Clique com o botão direto do mouse para Montar o Palete',
			IsGreatness: 'Grandeza',
			PreviousLot: 'Lote Anterior',
			InternalInventory: 'Inv. Interno',
			Elasticity: 'Elasticidade',
			Grammage: 'Gramatura',
			Tonality: 'Tonalidade',
			GenerateLabel: 'Gerar Etiqueta',
			Label: 'Etiqueta',
			CSVRequestImport: 'CSV das Entradas',
			Blockeda: 'Bloqueada',
			MeterRun: 'Metro Corrido',
			OrderProcessing: 'Ordem de Beneficiamento',
			SquareMeter: 'Metro Quadrado',
			Error_AddressHasProductCounted: 'Este endereço não pode ser contado como vazio, pois já existem produtos contados',
			Error_ProductHasACount: 'Este produto já possui contagem registrada',
			BlindNoteCheckNotStarted: 'Conferência desta Nota Cega não foi iniciada!',
			StorageFactorDifferentToSKUFactor: 'Fator do Produto quando internado esta divergente do cadastro. Realizar Inventário.',
			StorageAmmount: 'Qtd. Armazenagem',
			ChangesReport: 'Relatório de Trocas',
			PersonalizationLabels: 'Etiquetas da Personalização',
			QueryNegativeOrEmptyPicking: 'Consulta de Picking\'s Negativos/Zerados',
			CSVStockImport: 'CSV do Estoque',
			StockFile: 'Arquivo de Estoque',
			FilesPending: 'Existem arquivo pendentes, não é possível logar.',
			FilesPendingConfirmation: 'Existem arquivos pendentes de processamento, deseja visualizá-los?',
			PrintInfoInternation: 'Imprimir Informações de Internação',
			GenerateManifestPallet: 'Gerar Pallets do Manifesto',
			MaxWeightPallet: 'Peso Máximo do Pallet',
			ListPallets: 'Lista de Pallets',
			VehicleLicensePlate: 'Placa',
			VehicleMaintenance: 'Manutenção de Veículos',
			VehicleName: 'Nome do veículo',
			Vehicles: 'Veículos',
			Error_VehicleBrandRequired: 'Informe a marca do veículo',
			Error_VehicleLicensePlateRequired: 'É necessário informar a placa do veículo',
			Error_VehicleModelRequired: 'Informe o modelo do veículo',
			Error_VehicleNameRequired: 'Informe o nome do veículo',
			VehicleBrand: 'Marca',
			VehicleMaximumCubing: 'Cubagem máxima do veículo',
			VehicleMaximumPalletCubing: 'Cubagem máxima por palete',
			VehicleMaximumPalletWeight: 'Peso máximo por palete',
			VehicleMaximumWeight: 'Peso máximo do veículo',
			VehicleModel: 'Modelo',
			VehicleNumberOfPallets: 'Quantidade de paletes',
			MinStorageLevel: 'Nível Mínimo de Armazenagem',
			PalletMonitor: 'Monitor de Paletes do Manifesto',
			Error_ProductGroupNotExist: 'Grupo do produto não existe.',
			FantasyName: 'Nome Fantasia',
			CEP: 'CEP',
			Error_InvalidCEP: 'Digite o CEP',
			Box: 'Box',
			VehicleMinimumPalletWeight: 'Peso mínimo por palete',
			IP: 'IP',
			PrinterMaintenance: 'Manutenção de Impressoras IP',
			Error_FinalStreetRequired: 'Informe a rua final',
			Error_InitialStreetRequired: 'Informe a rua inicial',
			Error_IpRequired: 'Informe o IP',
			Error_PrinterNameRequired: 'Informe o nome da Impressora',
			Error_PrinterPortRequired: 'Informe a porta da Impressora',
			PrinterIp: 'IP da Impressora',
			PrinterName: 'Nome Impressora',
			PrinterPort: 'Porta da Impressora',
			GreatnessSeparation: 'Grandeza na Separação',
			PathfindExport: 'Exportação do arquivo de Pedidos - Pathfind',
			RouteClousure: 'Fechamento de Rota',
			HealthClassification: 'Classificação Sanitária',
			OSBreak: 'OSBreak',
			Select: 'Selecione',
			Notifications: 'Notificações',
			DaysWeek: 'Dias da Semana',
			Route: 'Rota',
			DefaultLayout: 'Layout Padrão',
			NestleBrokersLayout: 'Layout Brokers Nestlé',
			SelectLayout: 'Selecione o Layout',
			DeliveryDateRouter: 'Data de Remessa',
			FileLayout: 'Layout do Arquivo',
			PackNotOfThatOrder: 'Este pack não percente à esse pedido.',
			CST: 'CST',
			NCM: 'NCM',
			Contract: 'Contrato',
			ContractItems: 'Itens do contrato',
			NewContract: 'Novo Contrato',
			Periodicity: 'Periodicidade',
			CollectionPeriodicity: 'Periodicidade de Cobrança',
			AutomaticServices: 'TAG Serviços Automáticos',
			Note: 'Anotações',
			NoPicking: 'Sem Picking',
			TotalValue: 'Valor Total',
			COFINS: 'COFINS',
			ICMS: 'ICMS',
			PIS: 'PIS',
			NewTaxInformation: 'Nova Informação Fiscal',
			TaxInformation: 'Informação Fiscal',
			CFOP: 'CFOP',
			TaxTable: 'Tabela de Tributação',
			TaxTableName: 'Nome da Tabela de Tributação',
			IPI: 'IPI',
			ClientOperation: 'Operação de retirada do cliente',
			EnableProductKit: 'Kit de Produto',
			ProductKits: 'Produtos do Kit',
			Friday: 'Sexta',
			Monday: 'Segunda',
			RouteClosingDay: 'Dia de Fechamento da Rota',
			Saturday: 'Sábado',
			Sunday: 'Domingo',
			Thursday: 'Quinta',
			Tuesday: 'Terça',
			Wednesday: 'Quarta',
			StreetSeparation: 'Gerar Paletização por Rua',
			OrderServiceInternalMovement: 'OS de Movimentação Interna',
			DynamicPicking: 'Picking Dinâmico',
			InternalTransport: 'Transporte Interno',
			InternalTransportType: 'Tipo de Transporte Interno',
			Container: 'Recipiente',
			ContainerType: 'Tipo de Recipiente',
			TrayCart: 'Carrinho Bandeja',
			PlasticBox: 'Caixa Plástica',
			Cubing: 'Cubagem',
			PatrimonyTag: 'Etiqueta de Patrimônio',
			Inactive: 'Inativo',
			MultiOrders: 'Multi-Pedidos',
			OrderGroup: 'Grupo de Pedidos',
			AreYouSureToRemoveThisOrderGroup: 'Deseja remover o grupo de pedidos?',
			ActivityGuidedProfile: 'Perfil da Convocação Ativa',
			Profile: 'Perfil',
			ViewManifestPallet: 'Visualizar Pallets do Manifesto',
			GroupNameSeparationReleaseAdministration: 'Administração da Liberação da Separação',
			OrderGroupNameSeparationReleaseAdministration: 'Administração da Liberação da Separação por Grupo de Pedidos',
			GenerateMultiOrderFull: 'Gerar Multi-Pedidos Completo (Grandezas + Fracionados)',
			ViewMultiOrderFull: 'Visualizar Multi-Pedidos Completo (Grandezas + Fracionados)',
			LungDock: 'Pulmão-Doca',
			UpdateData: 'Data Atualização',
			ConfirmNewOrderServiceUMA: 'Confirmar mudança da internação referente a UMA informada?',
			PackingStation: 'Estação de Embalagem',
			ConfirmPackingStationConfigurationDialog: 'Confirmação do endereço da estação de embalagem?',
			Reversal: 'Estorno',
			UnitCodeSynonyms: 'Sinônimos',
			FileSubmissionReport: 'Painel de Integração Nestlé',
			SalesOrganization: 'Organização de Vendas',
			JustBlocked: 'Selecionar apenas endereços de produtos com algum tipo de bloqueio.',
			ShippingOutlet: 'Saída de Expedição',
			ShippingEntry: 'Entrada de Expedição',
			BlockedAudit: 'Auditoria de Bloqueados',
			VehicleTypeIntegrationCode: 'Tipo de Veículo',
			VehicleTypeSAPIntegrationCode: 'Código do Tipo de Veículo do SAP',
			VehicleTypePathfindIntegrationCode: 'Código do Tipo de Veículo do PathFind',
			ReasonRefusal: 'Motivo de Recusa',
			RefusedActivities: 'Atividades recusadas',
			RefusedActivitiesReport: 'Relatório de Atividades Recusadas',

		}
	});
})(jQuery);